### ISSUE TITLE
MACSposed not working with xiaomi ginkgo on Lineage-20

### ISSUE THREAD

**Issue by mast3rz3ro** [DavidBerdik/MACsposed#14] opened 2024-07-10 07:50 UTC
Hi,

I'm not able to change the MAC using the app "Change my MAC" when I try to change it's says send a feedback!

I have root with Magisk, and I'm able to run other LSPosed modules normally.

Waiting for any replies!

Thanks you!

**Comment by DavidBerdik** [comment] 2024-07-10 18:20
Hello @mast3rz3ro,

Thanks for your interest in MACsposed!

I have seen this issue occur with various MAC address spoofing apps on different phones. The problem is not with MACsposed itself, but rather, with the app you are using. All of the MAC address spoofing apps currently available were built for older versions of Android and therefore do not work consistently across all devices.

There are two solutions to this:

1. Try using another MAC address spoofing app with MACsposed. Unfortunately, I cannot recommend a specific app because there is no single app that works properly on all devices.
2. Wait for the release of MACsposed v1.2.0. This release will add support for MAC address spoofing directly to MACsposed and eliminate the need for using a third party application. Unfortunately, I cannot give you a timeline for when it will be ready for release, but I have been slowly working on it for a while now and hope to have it ready very soon.

**Comment by DavidBerdik** [comment] 2024-08-02 18:13
@mast3rz3ro MACsposed v1.2.0 is now available! I am going to close this issue now. If you are still having issues with spoofing with the new release, please let me know and I can investigate further.

**Closed by DavidBerdik** 2024-08-02 18:13 UTC
